# Generated by Django 6.0.6 on 2026-06-07 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.CreateModel(
            name='LinkedBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_id', models.CharField(max_length=100)),
                ('institution_name', models.CharField(max_length=200)),
                ('institution_logo', models.URLField(blank=True)),
                ('requisition_id', models.CharField(max_length=100, unique=True)),
                ('reference', models.CharField(max_length=36, unique=True)),
                ('gocardless_account_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Oczekuje na autoryzację'), ('linked', 'Połączone'), ('error', 'Błąd')], default='pending', max_length=10)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_banks', to='finance.account')),
            ],
            options={
                'verbose_name': 'Podlaczone konto',
                'verbose_name_plural': 'Podlaczone konta',
                'ordering': ['-created_at'],
            },
        ),
    ]
