# Generated by Django 6.0.6 on 2026-06-21 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_transaction_external_id_linkedbankaccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LinkedBankAccount',
        ),
    ]
